# Generated by Django 5.1.3 on 2024-12-16 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KandangAyam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kandang', models.CharField(max_length=100)),
                ('kapasitas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ayam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50)),
                ('usia', models.IntegerField()),
                ('kandang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayam', to='appKandang.kandangayam')),
            ],
        ),
    ]
